version: "3.9"


services:
  spring:
    image: patrick204nqh/paboot:latest
    container_name: paboot-spring
    stdin_open: true
    tty: true
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/backend
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: paboot-postgres
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - paboot_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: paboot-mailhog
    ports:
      - 8025:8025
      - 1025:1025


volumes:
  paboot_data: